version: 2.1

workflows:
  version: 2
  commit:
    jobs:
      - renovate:
          context: [aws, renovate]
  nightly:
    jobs:
      - renovate:
          context: [aws, renovate]
    triggers:
      - schedule:
          # every day at 11:30 AM UTC
          cron: "30 11 * * *"
          filters:
            branches:
              only:
                - main
jobs:
  renovate:
    machine: true
    steps:
      - run:
          environment:
            LOG_LEVEL: debug
          command: |
            set -eux
            npx renovate \
            --onboarding false \
            --require-config true \
            --allow-custom-crate-registries true \
            --token ${RENOVATE_TOKEN} \
            --git-author "LuLu Bot <lulubot-github@protonmail.com>" \
            --autodiscover \
            ;
